/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NearbyRouteImport } from './routes/nearby'
import { Route as ImageAnalysisRouteImport } from './routes/image-analysis'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAnalyzeSymptomImageRouteImport } from './routes/api/analyze-symptom-image'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyRoute = NearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageAnalysisRoute = ImageAnalysisRouteImport.update({
  id: '/image-analysis',
  path: '/image-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeSymptomImageRoute = ApiAnalyzeSymptomImageRouteImport.update({
  id: '/api/analyze-symptom-image',
  path: '/api/analyze-symptom-image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/image-analysis': typeof ImageAnalysisRoute
  '/nearby': typeof NearbyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/analyze-symptom-image': typeof ApiAnalyzeSymptomImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/image-analysis': typeof ImageAnalysisRoute
  '/nearby': typeof NearbyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/analyze-symptom-image': typeof ApiAnalyzeSymptomImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/image-analysis': typeof ImageAnalysisRoute
  '/nearby': typeof NearbyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/analyze-symptom-image': typeof ApiAnalyzeSymptomImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/auth'
    | '/history'
    | '/image-analysis'
    | '/nearby'
    | '/sitemap.xml'
    | '/api/analyze-symptom-image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/auth'
    | '/history'
    | '/image-analysis'
    | '/nearby'
    | '/sitemap.xml'
    | '/api/analyze-symptom-image'
  id:
    | '__root__'
    | '/'
    | '/assessment'
    | '/auth'
    | '/history'
    | '/image-analysis'
    | '/nearby'
    | '/sitemap.xml'
    | '/api/analyze-symptom-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentRoute: typeof AssessmentRoute
  AuthRoute: typeof AuthRoute
  HistoryRoute: typeof HistoryRoute
  ImageAnalysisRoute: typeof ImageAnalysisRoute
  NearbyRoute: typeof NearbyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAnalyzeSymptomImageRoute: typeof ApiAnalyzeSymptomImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby': {
      id: '/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof NearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-analysis': {
      id: '/image-analysis'
      path: '/image-analysis'
      fullPath: '/image-analysis'
      preLoaderRoute: typeof ImageAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-symptom-image': {
      id: '/api/analyze-symptom-image'
      path: '/api/analyze-symptom-image'
      fullPath: '/api/analyze-symptom-image'
      preLoaderRoute: typeof ApiAnalyzeSymptomImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentRoute: AssessmentRoute,
  AuthRoute: AuthRoute,
  HistoryRoute: HistoryRoute,
  ImageAnalysisRoute: ImageAnalysisRoute,
  NearbyRoute: NearbyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAnalyzeSymptomImageRoute: ApiAnalyzeSymptomImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
